### ISSUE TITLE
config.lazyload.enable 

### ISSUE THREAD

**Issue by debugly** [hifun-team/hexo-theme-miracle#22]
scripts.ejs:36 出错了，找不到 enable 属性，我修改了下，本地可以运行了

<% if (config.lazyload && config.lazyload.enable && (is_page() || is_post())){ %>

```
.../node_modules/hexo-theme-miracle/layout/_partial/scripts.ejs:36
      34| <% } %>
      35| 
   >> 36| <% if (config.lazyload.enable && (is_page() || is_post())){ %>
      37| <script>
      38|         try {
      39|             var io = new IntersectionObserver(function (entries) {
  
  Cannot read properties of undefined (reading 'enable')
      at eval ("/Users/matt/Documents/Preview-Markdown/node_modules/hexo-theme-miracle/layout/_partial/scripts.ejs":24:28)
      at scripts (/Users/matt/Documents/Preview-Markdown/node_modules/ejs/lib/ejs.js:692:17)
      at _View._compiledSync (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval ("/Users/matt/Documents/Preview-Markdown/node_modules/hexo-theme-miracle/layout/_partial/foot.ejs":134:17)
      at foot (/Users/matt/Documents/Preview-Markdown/node_modules/ejs/lib/ejs.js:692:17)
      at _View._compiledSync (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval ("/Users/matt/Documents/Preview-Markdown/node_modules/hexo-theme-miracle/layout/layout.ejs":24:17)
      at layout (/Users/matt/Documents/Preview-Markdown/node_modules/ejs/lib/ejs.js:692:17)
      at _View._compiled (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:39:17)
      at /Users/matt/Documents/Preview-Markdown/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/matt/Documents/Preview-Markdown/node_modules/bluebird/js/release/async.js:86:9) {
    path: '/Users/matt/Documents/Preview-Markdown/node_modules/hexo-theme-miracle/layout/layout.ejs'
  }
} Render HTML failed: index.html
```

**Comment by ocoke** [comment]
嗯是的，目前正在寻找更好的解决方法。在文档中有提到过要手动在 `_config.yml` 中添加 `lazyload` 和 `webp` 两个选项。

**Comment by ocoke** [comment]
这个方法是有效的，感谢。
